apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-rest
  namespace: hobbyfarm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo-rest
          image: {{ $.Values.mongo.image }}
          ports:
            - containerPort: {{ $.Values.mongo.containerPort }}
          env:
            - name: MONGO_URI
              value: {{ $.Values.mongo.uri }}
            - name: DB_NAME
              value: {{ $.Values.mongo.db }}
            - name: COLLECTION_NAME
              value: {{ $.Values.mongo.collection }}
