apiVersion: v1
kind: Service
metadata:
  labels:
    app: my-mongodb-svc
  name: mongo-db-service
  namespace: hobbyfarm
spec:
  ports:
    - protocol: TCP
      port: 27017
      targetPort: 27017
  selector:
    app: mongo
  type: NodePort
