apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
  name: my-mongodb
  namespace: hobbyfarm
spec:
  members: {{ $.Values.mongo.replicas }}
  type: ReplicaSet
  version: "4.2.6"
  security:
    authentication:
      modes: [ "SCRAM" ]
  users:
    - name: adminuser
      db: admin
      passwordSecretRef:
        name: mongo-creds
      roles:
        - name: readWrite
          db: {{ $.Values.mongo.db }}
      scramCredentialsSecretName: my-mongodb-credentials
  statefulSet:
    spec:
      serviceName: my-mongodb-svc
      template:
        spec:
          containers:
            - name: mongod
              resources:
                requests:
                  cpu: "100m"
                  memory: "500Mi"
                limits:
                  cpu: "300m"
                  memory: "2Gi"

            - name: mongodb-agent
              resources:
                requests:
                  cpu: "100m"
                  memory: "400Mi"
                limits:
                  cpu: "200m"
                  memory: "500Mi"
