apiVersion: v1
kind: Service
metadata:
  labels:
    app: rest
  name: mongo-service
  namespace: hobbyfarm
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30969
  selector:
    app: rest
  type: NodePort
