apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-rest
  namespace: hobbyfarm
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rest
  template:
    metadata:
      labels:
        app: rest
    spec:
      containers:
        - name: mongo-rest
          image: {{ $.Values.mongo.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ $.Values.mongo.restContainerPort }}
          env:
            - name: mongoURI
              value: {{ $.Values.mongo.uri }}
            - name: dbName
              value: {{ $.Values.mongo.db }}
            - name: collectionName
              value: {{ $.Values.mongo.collection }}
