apiVersion: v1
kind: Service
metadata:
  labels:
    app: mongo-service
  name: mongo-service
  namespace: hobbyfarm
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  selector:
    app: mongo-service
  type: NodePort
